openapi: "3.0.0"
info:
  version: 1.0.0
  title: Recipe DB
  license:
    name: MIT
servers:
  - url: https://recipe.jonfuller.me/v1
paths:
  /recipes:
    get:
      summary: List all recipes
      operationId: listRecipes
      tags:
        - recipes
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of recipes
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recipes"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a recipe
      operationId: createRecipes
      tags:
        - recipes
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /recipes/{recipeId}:
    get:
      summary: Info for a specific recipe
      operationId: showRecipeById
      tags:
        - recipes
      parameters:
        - name: recipeId
          in: path
          required: true
          description: The id of the recipe to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recipe"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Recipe:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Recipes:
      type: array
      items:
        $ref: "#/components/schemas/Recipe"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string